### ISSUE TITLE
Question Regarding a test run

### ISSUE THREAD

**Issue by miladabbasicorus** [awaragi/mocha-testrail-reporter#10]
Hi @awaragi 
After my test run, when the results are about to publish I'm receiving the following error. Can you please assist.
``` Publishing 7 test result(s) to https://instance.testrail.net/index.php
Error: undefined
D:\node_modules\mocha\lib\runner.js:910
    throw err;
    ^

Error: Error: got 404 response
    at \node_modules\mocha-testrail-reporter\dist\lib\testrail.js:28:27
    at Request.handleRequestResponse [as _callback] (D:\node_modules\unirest\index.js:463:26)
    at Request.self.callback (D:\node_modules\unirest\node_modules\request\request.js:187:22)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (D:\node_modules\unirest\node_modules\request\request.js:1044:10)
    at Request.emit (events.js:315:20)
    at IncomingMessage.<anonymous> (D:\node_modules\unirest\node_modules\request\request.js:965:12)
    at IncomingMessage.emit (events.js:327:22)
    at endReadableNT (_stream_readable.js:1221:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)
```

**Comment by awaragi** [comment]
Can you please share you runtime configuration? My guess is that your testrail instance is not reacheable from the command line. Try using curl to test it out first.

**Comment by miladabbasicorus** [comment]
@awaragi will do .. my current runtime is 
``` mocha  --timeout 300000 --color --reporter mocha-testrail-reporter --reporter-options domain=instance.testrail.net,username=*******,password=*******,projectId=P24,suiteId=S106 ./stacktest/test/index.js "
```
Thank you for the quick response :)

**Comment by miladabbasicorus** [comment]
fixed. As you mentioned it was an issue with my testrail instance. Thank you
