### ISSUE TITLE
Could not load reporter by name: cypress-testrail-reporter

### ISSUE THREAD

**Issue by suryawiguna** [awaragi/mocha-testrail-reporter#14]
I'm trying to integrate cypress and testrail using cypress-testrail-reporter, but when I run 
`npx cypress run --spec "cypress/integration/1_General/01_Change_Language.js"`

This error occured : 
```
suryambp:cypress suryawiguna$ npx cypress run --spec "cypress/integration/1_General/01_Change_Language.js"
Could not load reporter by name: cypress-testrail-reporter

We searched for the reporter in these paths:

- /Users/suryawiguna/Documents/works/igloocompany/iglooworks/cypress/cypress-testrail-reporter
- /Users/suryawiguna/Documents/works/igloocompany/iglooworks/cypress/node_modules/cypress-testrail-reporter

The error we received was:

Error: Could not locate the bindings file. Tried:
 → /Users/suryawiguna/Documents/works/igloocompany/iglooworks/cypress/node_modules/deasync/build/deasync.node
 → /Users/suryawiguna/Documents/works/igloocompany/iglooworks/cypress/node_modules/deasync/build/Debug/deasync.node
 → /Users/suryawiguna/Documents/works/igloocompany/iglooworks/cypress/node_modules/deasync/build/Release/deasync.node
 → /Users/suryawiguna/Documents/works/igloocompany/iglooworks/cypress/node_modules/deasync/out/Debug/deasync.node
 → /Users/suryawiguna/Documents/works/igloocompany/iglooworks/cypress/node_modules/deasync/Debug/deasync.node
 → /Users/suryawiguna/Documents/works/igloocompany/iglooworks/cypress/node_modules/deasync/out/Release/deasync.node
 → /Users/suryawiguna/Documents/works/igloocompany/iglooworks/cypress/node_modules/deasync/Release/deasync.node
 → /Users/suryawiguna/Documents/works/igloocompany/iglooworks/cypress/node_modules/deasync/build/default/deasync.node
 → /Users/suryawiguna/Documents/works/igloocompany/iglooworks/cypress/node_modules/deasync/compiled/14.15.1/darwin/x64/deasync.node
 → /Users/suryawiguna/Documents/works/igloocompany/iglooworks/cypress/node_modules/deasync/addon-build/release/install-root/deasync.node
 → /Users/suryawiguna/Documents/works/igloocompany/iglooworks/cypress/node_modules/deasync/addon-build/debug/install-root/deasync.node
 → /Users/suryawiguna/Documents/works/igloocompany/iglooworks/cypress/node_modules/deasync/addon-build/default/install-root/deasync.node
 → /Users/suryawiguna/Documents/works/igloocompany/iglooworks/cypress/node_modules/deasync/lib/binding/node-v87-darwin-x64/deasync.node
    at bindings (/Users/suryawiguna/Documents/works/igloocompany/iglooworks/cypress/node_modules/bindings/bindings.js:126:9)
    at Object.<anonymous> (/Users/suryawiguna/Documents/works/igloocompany/iglooworks/cypress/node_modules/deasync/index.js:30:31)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12789)
    at Function.Module._load (/Users/suryawiguna/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/override_require.js:15:27)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/suryawiguna/Documents/works/igloocompany/iglooworks/cypress/node_modules/cypress-testrail-reporter/dist/testrail.js:52:15)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12789)
    at Function.Module._load (/Users/suryawiguna/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/override_require.js:15:27)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/suryawiguna/Documents/works/igloocompany/iglooworks/cypress/node_modules/cypress-testrail-reporter/dist/cypress-testrail-reporter.js:21:18)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12789)
    at Function.Module._load (/Users/suryawiguna/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/override_require.js:15:27)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/Users/suryawiguna/Documents/works/igloocompany/iglooworks/cypress/node_modules/cypress-testrail-reporter/index.js:1:18)
    at Module._compile (internal/modules/cjs/loader.js:1078:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1108:10)
    at Module.load (internal/modules/cjs/loader.js:935:32)
    at Module._load (internal/modules/cjs/loader.js:776:14)
    at Function.f._load (electron/js2c/asar_bundle.js:5:12789)
    at Function.Module._load (/Users/suryawiguna/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/override_require.js:15:27)
    at Module.require (internal/modules/cjs/loader.js:959:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Function.loadReporter (/Users/suryawiguna/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/reporter.js:524:14)
    at ProjectE2E.watchSettingsAndStartWebsockets (/Users/suryawiguna/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/project-base.js:270:36)
    at /Users/suryawiguna/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/lib/project-base.js:142:49
    at tryCatcher (/Users/suryawiguna/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/util.js:16:23)
    at Promise._settlePromiseFromHandler (/Users/suryawiguna/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:547:31)
    at Promise._settlePromise (/Users/suryawiguna/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:604:18)
    at Promise._settlePromise0 (/Users/suryawiguna/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:649:10)
    at Promise._settlePromises (/Users/suryawiguna/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/promise.js:729:18)
    at _drainQueueStep (/Users/suryawiguna/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:93:12)
    at _drainQueue (/Users/suryawiguna/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:86:9)
    at Async._drainQueues (/Users/suryawiguna/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:102:5)
    at Immediate.Async.drainQueues [as _onImmediate] (/Users/suryawiguna/Library/Caches/Cypress/7.3.0/Cypress.app/Contents/Resources/app/packages/server/node_modules/bluebird/js/release/async.js:15:14)
    at processImmediate (internal/timers.js:461:21)


Learn more at https://on.cypress.io/reporters
```

Did I miss something here? I found same issue that posted on stackoverflow but no one answer it yet https://stackoverflow.com/questions/67420594/could-not-load-reporter-by-name-cypress-testrail-reporter

### cypress.json
```
{
    ...
    "reporter": "cypress-testrail-reporter",
    "reporterOptions": {
        "host": "iglooworks.testrail.io",
        "username": "adikurniawan@igloohome.co",
        "password": "Um3Jst0JL.ayoguEpqth",
        "projectId": 2,
        "suiteId": 9
    },
    ...
}
```

### package.json
```
{
    ...
    "devDependencies": {
        "cypress": "^7.3.0",
        "cypress-file-upload": "^4.1.1",
        "cypress-multi-reporters": "^1.4.0",
        "cypress-testrail-reporter": "^1.2.8",
        "mocha": "^8.2.1",
        "mochawesome": "^6.2.1",
        "mochawesome-merge": "^4.2.0",
        "mochawesome-report-generator": "^5.1.0"
      },
     ...
}
```

### 01_Change_Language.js
```
...
it('C2504 Change Language to Chinese', () => {
      cy.get('#languageZhDesktop').click()
      cy.wait(3000);
      cy.get('.mainTitleLogin').should('have.text', '控制面板')
})
...
```

**Comment by kj-brown** [comment]
This is probably one for @mickosav

**Comment by paragas12** [comment]
I am also facing the same issue.
@mickosav can you please help us.

**Comment by mnajibb** [comment]
Can somebody please explain to me why is this issue is still appear? (until i write this file) and why the author is somehow not reacting to this issue? at least tell us why it happen or a workaround? i faced this issue and got blocked by this. Please tell us or workaround or any fix that needed so that we will not got getting kicked out by our company 👍  @mickosav
